# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IntroWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5 import QtCore, QtGui, QtWidgets
import MenuWindow
import webbrowser


class introWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1600, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("QWidget{\n"
        "    background-color: rgb(255, 255, 255)\n"
        "}\n"
        "QLabel{\n"
        "    background-color: rgb(255,255,255,0);\n"
        "}\n"
        "QPushButton{\n"
        "    border:1px solid rgb(84, 84, 85);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 12px;\n"
        "    border-radius: 8px;\n"
        "    border-bottom: 4px solid grey;\n"
        "    \n"
        "    color: rgb(0, 0, 0)\n"
        "}")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(580, 130, 451, 431))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/kkambback.jpg"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1130, 770, 191, 81))
        font = QtGui.QFont()
        font.setFamily("여기어때 잘난체 OTF")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(480, 560, 661, 81))
        font = QtGui.QFont()
        font.setFamily("여기어때 잘난체 OTF")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1350, 770, 191, 81))
        font = QtGui.QFont()
        font.setFamily("여기어때 잘난체 OTF")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 0, 101, 71))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("images/kdata_og.jpg"))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, -10, 181, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/korea_univ.png"))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(640, 660, 341, 31))
        font = QtGui.QFont()
        font.setFamily("여기어때 잘난체 OTF")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        Form.setCentralWidget(self.centralwidget)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.btn_go_to_menu)
        self.pushButton_2.clicked.connect(Form.btn_github)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "IntroWindow"))
        self.pushButton.setText(_translate("Form", "Start!"))
        self.label_2.setText(_translate("Form", "Protect Your Vision"))
        self.pushButton_2.setText(_translate("Form", "Git Hub"))
        self.label_5.setText(_translate("Form", "당신의 눈을 지켜드립니다"))
    def btn_go_to_menu(self): 
        self.hide()                   
        self.change = MenuWindow.menuwindow()    
        self.change.show()    

    def btn_github(self):
        webbrowser.open('https://github.com/orgs/DatacampusTeam14/repositories')

    def Quit(self):
        exit()

if __name__ == "__main__":
    import sys
    App = QApplication(sys.argv)
    ui = introWindow()
    ui.show()
    sys.exit(App.exec_())
