# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cupang.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys,os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
import cupang_selenium_food,MenuWindow

path="C:\\blink_project-master\\UI_v13\\images\\" ##경로 설정 중요
cupang_selenium_food.cupangimage()
class cupang(QWidget):
    
  
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        #self.centralwidget = QtWidgets.QWidget(MainWindow)
        #self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(MainWindow)
        self.lineEdit.setGeometry(QtCore.QRect(300, 510, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(40, 30, 480, 640))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(path+"눈에 좋은 약_0.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(560, 30, 480, 640))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(path+"눈에 좋은 약_1.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(1080, 30, 480, 640))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(path+"눈에 좋은 약_2.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")            
        self.pushButton = QtWidgets.QPushButton(MainWindow)
        self.pushButton.setGeometry(QtCore.QRect(1290, 740, 101, 81))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(1440, 740, 101, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.return_menu)
        #MainWindow.setCentralWidget(MainWindow)
        #self.menubar = QtWidgets.QMenuBar(MainWindow)
        #self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        #self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(MainWindow)
        #self.statusbar = QtWidgets.QStatusBar(MainWindow)
        #self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(MainWindow)
    
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def return_menu(self):
        self.close()                     
        self.mw = MenuWindow.menuwindow()
        self.mw.show()

        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "돌아가기"))
        self.pushButton_2.setText(_translate("MainWindow", "나가기"))




# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = cupang() #클래스
#     ui.setupUi(MainWindow) #클래스 내에 있는 정의문 setupUI
#     MainWindow.show()
#     sys.exit(app.exec_())

if __name__ == "__main__":
    app = QApplication(sys.argv)
    ui = cupang()
    ui.show()
    sys.exit(app.exec_())